
   const doctor = [
    { name: "daniel" },
    { name: "ruth" },
    { name: "Gediyonbbbblaksdflaksdflkasdlfknalskdasdbb" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
    { name: "ruth" },
    { name: "Gediyon" },
    { name: "Alazar" },
  ];
 const doctorprofile = {
    "id": 1,
    "name": "Dani Kebede",
    "profile_picture": "https://randomuser.me/api/portraits/men/75.jpg",
    "work": "Software Engineer",
    "payment":"200 ETB/Session",
    "non-availabTime":{'2025-05-02':[0,1,2,3,4,5,6,7],'2025-05-03':[2,4,5]}
}
export default{
  doctor,
  doctorprofile
};
